### ISSUE TITLE
Rename to lodash-modularize

### ISSUE THREAD

**Issue by thejameskyle** [megawac/babel-plugin-lodash#1]
For the reasons I mentioned in chat

**Comment by jdalton** [comment]
?

**Comment by megawac** [comment]
As seen in chat

> thejameskyle: @megawac not to nitpick but babel-plugin names like "lodash" or "ramda" are exactly in line with the more descriptive titles we have today
jmeas: :police_car:
thejameskyle: : It's kinda annoying when people create packages like "babel-plugin-jsx" that do one specific thing with jsx because it's like name squatting
jmeas: makes sense
megawac: take me to :post_office:
jmeas: ROFL
thejameskyle: Like this is how descriptive we like them https://github.com/babel-plugins/babel-plugin-object-create-multiple-to-single-and-define-property
:stuck_out_tongue_winking_eye:
(this is an exaggerated example)
jmeas: im going to make
babel-plugin-plugin
does w.e. i want it to
megawac: yeah I was going to originally call them <x>-modularize
but I couldn't see any other meaningful plugins taking that namespace so said f it
jmeas: lol
jmeas: aliases!!!
jridgewell: @thejameskyle That's why the @babel scope would be perfect for this 6.0 discussion.
jridgewell: @babel/plugin-constant-folding = Official bable plugin
thejameskyle: @jridgewell I still think that's a bit separate. babel-plugin-lodash doesn't really mean what it does
babel-plugin-constant-folding = Unofficial bable plugin
I could write a babel plugin that replaces inline helpers with lodash methods or something that would kinda conflict

**Comment by jdalton** [comment]
Thanks for bringing this up! Lodash is set to adopt this as the official lodash babel plugin.

**Comment by thejameskyle** [comment]
That's still not good, the name should describe what it does and it currently does not.

**Comment by jdalton** [comment]
It get's a little sticky with how plugins [are resolved too](https://github.com/babel/babel/blob/7918b9028bbd5ebc578776adfeee8276429b3dc3/packages/babel-core/src/transformation/file/options/option-manager.js#L130):
```js
let pluginLoc = resolve(`babel-plugin-${plugin}`, dirname) || resolve(plugin, dirname);
```
because if `babel-plugin-lodash` is missing it'll try `resolve('lodash', dirname)` but as far as squatting goes if it's under lodash core I'm cool with it. Since webpack and rollup are unable to address tree-shaking for something as robust as lodash having a simply named official plugin is fine. We'll likely expand with plugin options in the future too which is another reason keep things a bit loose with the name.
